apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-api
  labels:
    app: autoware-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoware-api
  template:
    metadata:
      labels:
        app: autoware-api
    spec:
      hostNetwork: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 986
      containers:
      - name: autoware-api
        image: sudharsansabesh/autoware-sim:universe-devel
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args:
          - |
            source /opt/autoware/setup.bash
            ros2 launch tier4_autoware_api_launch autoware_api.launch.xml init_simulator_pose:=true init_localization_pose:=false 
        env:
        - name: RMW_IMPLEMENTATION
          value: rmw_fastrtps_cpp
        - name: ROS_HOME
          value: /autoware_data/.ros
        - name: ROS_LOG_DIR
          value: /autoware_data/.ros/log
        - name: TZ
          value: Etc/UTC
        volumeMounts:
        - name: map-vol
          mountPath: /autoware_map
          readOnly: true
        - name: data-vol
          mountPath: /autoware_data
      volumes:
      - name: map-vol
        persistentVolumeClaim:
          claimName: map-pvc
      - name: data-vol
        persistentVolumeClaim:
          claimName: data-pvc