---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: map-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/ros/autoware_map/sample-map-rosbag"   
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/ros/autoware_data"                    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: map-pvc
spec:
  storageClassName: local-path
  volumeName: map-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  storageClassName: local-path
  volumeName: data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi